---
- name: install packages
  apt: name={{item}}
  with_items:
    - locales-all
    - ruby
    - ruby-dev
    - build-essential
    - zlib1g-dev
    - libcurl4-openssl-dev
- name: install apache packages
  apt: name={{item}}
  with_items:
    - apache2-threaded-dev
    - apache2-dev
    - apache2
  when: 
    - use_apache
    - item == "apache2-threaded-dev" and ansible_distribution_release == "wheezy"
    - item == "apache2-dev" and ansible_distribution_release == "wheezy"
- name: install bundler gem
  gem:
    name: bundler
    user_install: no
    pre_release: no
- name: install rack gem (depends by passenger)
  gem:
    name: rack
    user_install: no
    pre_release: no
    version: 1.6.5
  when: use_passenger and ansible_distribution_release in ["jessie", "wheezy"]
- name: install passenger gem
  gem:
    name: passenger
    user_install: no
    pre_release: no
  when: use_passenger
- name: install apache2 passenger module
  args:
  shell: |
    if find /var/lib/gems/*/gems/passenger-* -name mod_passenger.so | egrep -q '.so$'; then
      echo -n 'ok'
    else
      /usr/local/bin/passenger-install-apache2-module -a
      find /var/lib/gems/*/gems/passenger-* -name mod_passenger.so | egrep -q '.so$'
    fi
  register: chk_mod_passenger
  when: use_passenger and use_apache
  changed_when: chk_mod_passenger.stdout != 'ok'
- name: create passenger module config
  args:
    creates: /etc/apache2/mods-available/passenger.load
  shell: |
    echo 'LoadModule passenger_module '`ls /var/lib/gems/*/gems/passenger-*/buildout/apache2/mod_passenger.so |tail -1` > /etc/apache2/mods-available/passenger.load; \
    echo 'PassengerRoot '`ls -d /var/lib/gems/*/gems/passenger-* |tail -1` > /etc/apache2/mods-available/passenger.conf; \
    echo 'PassengerDefaultRuby '`gem env | grep 'RUBY EXECUTABLE:' | awk '{print $4}'` >> /etc/apache2/mods-available/passenger.conf; \
    echo 'PassengerEnabled off' >> /etc/apache2/mods-available/passenger.conf
  when: use_passenger and use_apache
  notify: restart apache2
- name: enable passenger module
  args:
    creates: /etc/apache2/mods-enabled/passenger.load
  shell: a2enmod passenger
  when: use_passenger and use_apache
  notify: restart apache2
- name: enable apache modules
  args:
    creates: /etc/apache2/mods-enabled/{{item}}.load
  shell: a2enmod {{item}}
  with_items:
    - headers
    - expires
    - rewrite
  when: use_apache
  notify: restart apache2
- name: setup rvm running environment without sudo
  apt:
    name: "{{item}}"
  with_items:
    - curl
    - autotools-dev
    - bison
    - coreutils
    - file
    - libffi-dev
    - libgdbm-dev
    - libgmp-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - netbase
    - openssl
    - procps
    - zlib1g-dev
  when: use_rvm or use_rvm_depends
