---
- name: install fail2ban
  apt:
    name: fail2ban
- name: copy filters
  copy:
    src: "f2b-filter.{{item}}"
    dest: "/etc/fail2ban/filter.d/{{item}}.local"
  with_items:
    - sshd-probe
  notify: restart fail2ban
- name: copy jail rules
  template:
    src: "f2b-jail.{{item}}"
    dest: "/etc/fail2ban/jail.d/{{item}}.local"
  with_items:
    - postfix
    - sshd-ddos
    - sshd-probe
    - sshd
    - ignore
  notify: restart fail2ban
