---
- name: make sure to install python-apt
  shell: |
    if dpkg -l python-apt 2> /dev/null | egrep -q '^ii '; then
      echo -n ok
    else
      apt-get -y install python-apt
    fi
  register: check_python_apt
  changed_when: check_python_apt.stdout != "ok"
- name: add arege apt key
  apt_key:
    url: http://arege.jp/debian-arege/keys.gpg
  when: use_apt_upchk
- name: add apt-upchk repository
  apt_repository:
    repo: "deb http://ftp.arege.jp/debian-arege {{ansible_distribution_release}} apt-upchk"
- name: install base packages
  apt:
    name: "{{item}}"
  with_items:
    - locales-all
    - ntp
    - ntpdate
    - apt-transport-https
    - ca-certificates
- name: add apt-upchk
  apt:
    name: apt-upchk
  when: use_apt_upchk
- name: change sshd port
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "Port {{change_sshd_port if change_sshd_port and change_sshd_port != True else 2022}}"
    regexp: '^Port\s+\d+$'
  when: change_sshd_port
  notify: restart sshd
- name: send syslog *.err /var/log/errors
  copy:
    src: rsyslog-errors.conf
    dest: /etc/rsyslog.d/errors.conf
  notify: restart rsyslog
- name: exclude local.* from /var/log/syslog
  lineinfile:
    dest: /etc/rsyslog.conf
    line: "*.*;local0,local1,local2,local3,local4,local5,local6,local7,auth,authpriv.none	-/var/log/syslog"
    regexp: '^\*\.\*;\S+\s+-/var/log/syslog'
  notify: restart rsyslog
- name: add logrotate rule for /var/log/errors
  copy:
    src: logrotate.errors
    dest: /etc/logrotate.d/syslog-errors
- name: install logcheck
  apt:
    name: logcheck
- name: set logcheck logfiles
  copy:
    src: logcheck.logfiles
    dest: /etc/logcheck/logcheck.logfiles
- name: copy base logcheck ignore
  copy:
    src: logcheck.ignore
    dest: /etc/logcheck/ignore.d.server/nemui-base
- include: unattended_upgrade.yml
  when: use_unattended_upgrade
- include: fail2ban.yml
  when: use_fail2ban
- include: docker.yml
  when: use_docker
