---
- name: install unattended upgrade
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
- name: set upgrade packages to all
  blockinfile:
    insertafter: '^Unattended-Upgrade::Origins-Pattern {'
    marker: '// {mark} ANSIBLE MANAGED BLOCK'
    block: |
      "o=Debian,n=${distro_codename}-updates";
      "o=Debian,n=${distro_codename}-proposed-updates";
      "o=Debian,n=${distro_codename},label=Debian";
      "o=Debian,n=${distro_codename},label=Debian-Security";
      "o=Debian Backports,n=${distro_codename}-backports,l=Debian Backports";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
- name: set send mail when upgraded
  lineinfile:
    regexp: '^/?/?Unattended-Upgrade::Mail "'
    line: 'Unattended-Upgrade::Mail "root";'
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
- name: enable unattended upgrade
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
