---
- name: restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted
- name: restart td-agent
  service:
    name: td-agent
    state: restarted
- name: apply sysctl
  shell: sysctl -p /etc/sysctl.d/*.conf
