---
- name: restart sshd
  service:
    name: ssh
    enabled: true
    state: restarted
- name: restart rsyslog
  service:
    name: rsyslog
    enabled: true
    state: restarted
- name: restart fail2ban
  service:
    name: fail2ban
    enabled: true
    state: restarted
